version: '3.8'
services:
  backend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_API_URL=http://localhost:3000
    depends_on:
      - backend
