apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo-cluster
  region: ap-southeast-2
managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    ssh:
      allow: true

# nodeGroups:
#   - name: eks-node-group
#     instanceType: t3.micro
#     desiredCapacity: 3
#     privateNetworking: true

# fargateProfiles:
#   - name: acg-fargate-development
#     selectors:
#       - namespace: development