apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      serviceAccountName: todo-backend-sa
      containers:
      - name: todo-backend
        image: sujan/todo-backend:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: API_KEY
#
# If using AWS Secrets Manager with IRSA, update your app to fetch the secret using the AWS SDK at runtime.
# The serviceAccountName above enables the pod to assume the IAM role for secret access.
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
#
# To access this backend service from another pod in the same namespace, use:
#   http://todo-backend:3000
# as the BACKEND_API_URL environment variable in your frontend deployment.
